---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Setting up test environment.
      debug:
        msg:
          - '==============================================================='
          - 'Pre tasks'
          - '==============================================================='

    - name: Ensure Python requirements installed.
      apt:
        name:
          - mosquitto
          - nginx
          - ntp
          - python
          - python-pip
          - python-setuptools
          - python3-pip
          - python3-setuptools
        state: present

    - name: Ensure Pip requirements installed.
      pip:
        name:
          - flake8
          - requests
      become: false
      changed_when: false

  roles:
    - role: servicez
      configuration: https://is.gd/yBZCrb


  post_tasks:
    - name: Run verification tests.
      debug:
        msg:
          - '================================================================'
          - 'Post tasks'
          - '================================================================'

    - name: Get flake8 version.
      command: flake8 --version
      register: lint_version
      changed_when: false
      failed_when: '"pyflakes" not in lint_version.stdout'