---
- name: Prepare
  hosts: all

  tasks:
  - name: Ensure requirements are installed.
    apt:
      name:
        - mosquitto
        - nginx
        - ntp
        - python-pip
        - python-setuptools
        - python3-pip
        - python3-setuptools
      state: present
    become: true
